services:
  - type: web
    name: mmu-lost-and-found
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lostfound.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: AT_API_KEY
        sync: false
      - key: AT_USERNAME
        value: sandbox
      - key: CLOUDINARY_CLOUD_NAME
        value: dnkm4xw93
      - key: CLOUDINARY_API_KEY
        value: 239584521538991
      - key: CLOUDINARY_API_SECRET
        value: S4RPdOhHTrhhtn07a59KwzlTWK4
      - key: APP_URL
        value: https://mmu-lost-and-found.onrender.com

databases:
  - name: lostfound-db
    plan: free
