# Generated by Django 6.0.3 on 2026-03-31 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('DOCUMENTS', 'Documents'), ('CLOTHING', 'Clothing'), ('KEYS', 'Keys'), ('BAGS', 'Bags'), ('OTHER', 'Other')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPORTED_FOUND', 'Reported Found'), ('CLAIM_PENDING', 'Claim Pending'), ('RECOVERED', 'Recovered'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
