# Generated by Django 6.0.3 on 2026-03-31 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AddField(
            model_name='item',
            name='location_found',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('jewelry', 'Jewelry'), ('clothing', 'Clothing'), ('documents', 'Documents'), ('bags', 'Bags & Wallets'), ('books', 'Books'), ('keys', 'Keys'), ('glasses', 'Glasses'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('claimed', 'Claimed'), ('recovered', 'Recovered'), ('deactivated', 'Deactivated')], default='found', max_length=20),
        ),
    ]
