# Generated by Django 6.0.3 on 2026-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_owner_item_location_found_item_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('found', 'Found'), ('claimed', 'Claimed'), ('recovered', 'Recovered'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
    ]
