# Generated by Django 6.0.3 on 2026-03-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('finder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_found', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='items.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
