# Generated by Django 6.0.3 on 2026-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='finder_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
